services:
  - type: static
    name: hormigapp-front
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishPath: dist
    routes:
      # 1. Regla para archivos estáticos (evita la pantalla en blanco)
      - source: /assets/*
        destination: /assets/*
      # 2. Regla para el SPA (maneja el ruteo de React)
      - source: /*
        destination: /index.html
